### ISSUE TITLE
Projectboard naar FDND-Agency brengen

### ISSUE THREAD

**Issue by ju5tu5** [fdnd-agency/wogo#8]
Jullie werken samen aan een FDND-Agency project, breng het projectboard hier naartoe.

**Comment by mcphendriks** [comment]
Ik heb geen rechten om de issues naar het projectbord van FDND-agency over te zetten. Kunnen jullie mijn rechten geven zodat ik dit kan doen? @ju5tu5 @joostf 
https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects

**Comment by ju5tu5** [comment]
Als het goed is kan je het nu wel..
